### ISSUE TITLE
Unable to instantiate application

### ISSUE THREAD

**Issue by sumanwebidigital** [rno/WebRTC#2]
In 1.0.7 build encounter with a issue.

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.trackify.management.test_dev, PID: 11064
    java.lang.RuntimeException: Unable to instantiate application com.trackify.management.MainApplication package com.trackify.management.test_dev: java.lang.ClassNotFoundException: Didn't find class "com.trackify.management.MainApplication" on path: DexPathList[[zip file "/data/app/~~-GG07L6_baGyS_IXw3IYIQ==/com.trackify.management.test_dev-CEAuKQMCRlTtwX1nqUWgZw==/base.apk"],nativeLibraryDirectories=[/data/app/~~-GG07L6_baGyS_IXw3IYIQ==/com.trackify.management.test_dev-CEAuKQMCRlTtwX1nqUWgZw==/lib/arm64, /data/app/~~-GG07L6_baGyS_IXw3IYIQ==/com.trackify.management.test_dev-CEAuKQMCRlTtwX1nqUWgZw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1466)
        at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1395)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6746)
        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.trackify.management.MainApplication" on path: DexPathList[[zip file "/data/app/~~-GG07L6_baGyS_IXw3IYIQ==/com.trackify.management.test_dev-CEAuKQMCRlTtwX1nqUWgZw==/base.apk"],nativeLibraryDirectories=[/data/app/~~-GG07L6_baGyS_IXw3IYIQ==/com.trackify.management.test_dev-CEAuKQMCRlTtwX1nqUWgZw==/lib/arm64, /data/app/~~-GG07L6_baGyS_IXw3IYIQ==/com.trackify.management.test_dev-CEAuKQMCRlTtwX1nqUWgZw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
        at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1232)
        at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1458)
        at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1395) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6746) 
        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7898) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
    	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/trackify/remote/screenshare/LibraryBuilderListener;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        		... 16 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.trackify.remote.screenshare.LibraryBuilderListener" on path: DexPathList[[zip file "/data/app/~~-GG07L6_baGyS_IXw3IYIQ==/com.trackify.management.test_dev-CEAuKQMCRlTtwX1nqUWgZw==/base.apk"],nativeLibraryDirectories=[/data/app/~~-GG07L6_baGyS_IXw3IYIQ==/com.trackify.management.test_dev-CEAuKQMCRlTtwX1nqUWgZw==/lib/arm64, /data/app/~~-GG07L6_baGyS_IXw3IYIQ==/com.trackify.management.test_dev-CEAuKQMCRlTtwX1nqUWgZw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        		... 19 more
I/Process: Sending signal. PID: 11064 SIG: 9
`

**Comment by rno** [comment]
I don't think this is coming from the updated version of WebRTC.

Maybe you reached the upper limit and need to switch to MultiDex?
